### ISSUE TITLE
响应式布局技术方案调研

### ISSUE THREAD

**Issue by winnieBear** [winnieBear/bearBlog#1]
___

## 响应式布局?
>个人理解:
* 同一份html代码,根据屏幕的大小,选择*合适*的方式把内容展现给用户,在小屏幕下有可能只显示核心的内容,隐藏不重要的内容区域.其中*合适*的方式,一般取决于设计师的特意设计;一般响应式布局不同于移动端的自适应布局,不会随屏幕变化时时变化,而是根据设计师设计的break point，在这个点发生变化。
* 同一个内容区块在不同大小屏幕下展示的位置会发生变化，但是区块本身的宽度一般不变化，图片的大小也一般不变化，做的精细的会根据屏幕的dpi加载不同分辨率的图片，例如2x图，1.5x图等。
* 有的响应式在不同大小的屏幕展示的字体大小也会变化。
* 采用什么样的变化策略，以及屏幕尺寸的break point取决于需求方，没有固定的策略。

### Media Query 方案
响应式实现方案一般是采用Media Query方案，满足某种屏幕宽度时设置某些元素的css属性值来改变布局。例如

```css
/** iPhone **/
@media only screen and (min-width: 320px) and (max-width: 767px) {}

/** iPad **/
@media only screen and (min-width: 768px) and (max-width: 1024px) {}

```

Media Query 方案也是最流行的响应式布局方案，优缺点如下：

### 优点：
* 大部分浏览器原生支持，使用方便；
* 浏览器自动随着窗口变化使用相适应的css；
* 当使用sass来写样式时，可以把同一个区块的样式和其相关的Media Query 条件下的样式都写一块，便于维护，例如：

```css
 body {
     background: navy;
     @media #{$phone} {
         background: yellow;
     }

     @media #{$pad} {
         background: green;
     }
     /* ... */
 }

 //编译后
 body{
     background: navy;
 }
 @media only screen and (min-width: 320px) and (max-width: 767px) {
     body{
         background: yellow;
     }
 }

 @media only screen and (min-width: 768px) and (max-width: 1024px) {
     body{
         background: green;
     }
 }

 /* ... */

```

### 缺点
* ie8 不支持Media Query,不过可以通过一个ployfill的[Respond.js](https://github.com/scottjehl/Respond)来fix，但是这个js的原理是把所有css都通过一个函数进行转换，如果是外联的css需要异步请求这个css,如果你的css是放在CDN上，异步请求时存在跨域问题，这个ployfill提供了一种iframe通过window.name的方式来进行跨域请求的方案，但是需要一个proxy的html放在跟css放在同域名下才可以，我们这目前不能上传html到css的CDN上；我改了一个版本[Respond.js](https://github.com/winnieBear/Respond)，因为我们CDN都做了CORS的响应头，高级的浏览器直接通过ajax可以跨域请求，ie8，ie9只能通过XDomainRequest来进行跨域请求。

* 样式可以通过Media Query的方法来实现，但是不同尺寸屏幕下的js交互逻辑也是需要跟屏幕尺寸匹配起来。例如不同屏幕下执行的js逻辑不一样，这个js逻辑同时要跟展现的dom要匹配起来。
目前[Window.matchMedia()](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia)支持通过js方法查询当前窗口的宽度，然后执行响应的js逻辑，例如：

```js
if (window.matchMedia("(min-width: 400px)").matches) {
  /* the viewport is at least 400 pixels wide */
} else {
  /* the viewport is less than 400 pixels wide */
}
```
但是IE 10以下不支持，[matchMedia.js](https://github.com/paulirish/matchMedia.js)提供了ployfill可以使得IE 9 <del>及以下</del> 的浏览器支持`window.matchMedia`，但是IE8不支持。
同时为了方便的使用js来查询Media Query和添加响应的逻辑，引入另外一个[enquire.js](https://github.com/WickyNilliams/enquire.js),前提是添加了matchMedia.js ployfill，使用方法：

```js
enquire.register("screen and (max-width:1000px)", {

    match : function() {},      // OPTIONAL
                                // If supplied, triggered when the media query transitions
                                // *from an unmatched to a matched state*

    unmatch : function() {},    // OPTIONAL
                                // If supplied, triggered when the media query transitions
                                // *from a matched state to an unmatched state*.
                                // Also may be called when handler is unregistered (if destroy is not available)

    setup : function() {},      // OPTIONAL
                                // If supplied, triggered once immediately upon registration of the handler

    destroy : function() {},    // OPTIONAL
                                // If supplied, triggered when handler is unregistered. Place cleanup code here

    deferSetup : true           // OPTIONAL, defaults to false
                                // If set to true, defers execution the setup function
                                // until the media query is first matched. still triggered just once
});

```

### 自己写js实现
在页面的head里添加js代码，判断屏幕的宽度，根据屏幕宽度来给dom根元素设置相对应的样式例如'small','large'等，同时在window下设置一个全局变量标识当前是哪一种类型，例如`window.size=small;`，然后在css中通过不同的前缀选择器设置某些元素的css属性值来改变布局。例如

```js
//head中添加判断js
(function(doc, win) {
    var w, clsName, response = {
        size: void 0,
        width: void 0,
        calWinSize: void 0,
        arrCallback: []
    };
    win.response = response;

    var root = doc.documentElement,
        db = doc.body;

    //w3c: window.innerWidth
    //ie quirks mode: document.body.clientWidth
    //ie stantdard mode: document.documentElement.clientWidth

    function calWinSize() {
        //console.info('calWinSize ...')
        w = win.innerWidth || (root && root.clientWidth) || (db && db.clientWidth);
        clsName = 'normal';
        if (w <= 768) {
            clsName = 'small';
        } else if (w > 1600) {
            clsName = 'large';
        }
        if (response.clsName !== clsName) {
            var oldClsName = response.clsName;
            // 标记CSS
            root.className = clsName;
            // 标记JS
            response.clsName = clsName;
            //exec callback
            for (var i = 0, len = response.arrCallback.length; i < len; i++) {
                response.arrCallback[i](oldClsName, clsName);
            }
        }

        response.width = w;
        console.info(w, clsName)
    }
    response.calWinSize = calWinSize;


    var addEvent = (function() {
        if (window.addEventListener) {
            return function(element, eventName, callback) {
                element.addEventListener(eventName, callback, false);
            }
        } else {
            return function(element, eventName, callback) {
                element.attachEvent('on' + eventName, callback);
            }
        }
    })();

    //calculate window size
    calWinSize();
    addEvent(window, 'resize', calWinSize);

})(document, window);

```

```css
/** small **/
.small body {
    background: yellow;
}

/** normal **/
.normal body {
    background: green;
}

/* large */
.large body{
    background: navy;
}

```

### 优点
* 不存在浏览器兼容性，不需要额外的ployfill
* css和js的逻辑保持一致,处理方便；

### 缺点
* 当使用sass来写样式时，同一个区块的样式在不同前缀下的定义是分割开来的，导致维护稍有不便；
* 浏览器渲染时需要先执行这段js，但对性能影响不大；

## 响应式布局下区块呈现的方法
有多种方式可以实现在保持dom元素不变，改变css的设置来变换元素的布局。

dom结构

```html
<div class="wrapper a">
    <div class="a1">
        御林军VS延边队鹿死谁手？
    </div>
    <div class="a2">
        御林军VS延边队鹿死谁手？
    </div>
    <div class="a3">
        御林军VS延边队鹿死谁手？
    </div>
</div>
```

### Float

```css
.a {
    @extend %clearfix;
    .a1, .a2, .a3{
        float: left;
        padding-left: 1em;
        margin-bottom: 10px;
    }



     @include mq-phone {
         .a1, .a2, .a3 {

             float:none;
             width: 100%;
         }
     }

     @include mq-pad {
         .a1 {
             width: 100%;
         }
         .a2, .a3{
             width: 50%;
         }
     }
}
```
总结：float对于这种自适应布局处理起来比较简单方便。

### Display:table-cell
Display:table-cell被ie8支持，可以应用在很多地方。

```css
.b {
    display: table;
    width: 100%;

    .a1, .a2, .a3{
        display: table-cell;
        padding-left: 1em;
        margin-bottom: 10px;
    }

     @include mq-phone {
         .a1, .a2, .a3 {
             width: 100%;
             display: block;
         }
     }

     @include mq-pad {
         .a1 {
             display: table-caption;
             width: 100%;
         }
         .a2, .a3{
             width: 50%;
         }
     }
}
```
总结：这种方法适合所有都展示在一行，容器需要设置为display: table;如果需要把某个元素独占一行,需要设置为display: table-caption;
但是只能在任意位置独占一行，只能在所有元素的上面独占一行，有一定的局限性。

### display:inline-block

```css
.d {
    font-size: 0;

    .a1, .a2, .a3{
        display: inline-block;
        padding-left: 1em;
        margin-bottom: 10px;
        font-size: 16px;
        vertical-align: top;
    }

     @include mq-phone {
         .a1, .a2, .a3 {
             width: 100%;
         }
     }

     @include mq-pad {
         .a1 {
             width: 100%;
         }
         .a2, .a3{
             width: 50%;
         }
     }
}
```
总结：这种方法跟float在很多地方相似，处理也比较方便，唯一需要处理的是因为inline-block元素之间的间隙（父容器设置font-size:0,ie8以上和其他高级浏览器支持），还有inline-block元素之间的垂直方向的对齐。

### postion:absolute

```css
.c {
    position: relative;
    width: 100%;

    .a1, .a2, .a3, .a4 {
        padding-left: 1em;
        margin-bottom: 10px;
    }

     @include mq-phone {
         height: auto;
         .a1, .a2, .a3, .a4{
             position: static;
             width: 100%;
             display: block;
         }
     }

     @include mq-pad {
         .a1, .a4{
            position: static;
            width: 100%;
         }
         .a2, .a3{
             width: 50%;
         }
         .a2{
             margin-left: 0;
             margin-right: 50%;
         }
         .a3{
             position: absolute;
             top:143.33px;
             right: 0;
         }
     }

}
```
总结：这种方法如果只有独占一行或者并排显示这两种逻辑还可以，如果要实现个别独占一行，有的又想并排显示处理特别麻烦，不推荐使用。

## 响应式布局的窗口break-point

* phone: < 768px
* pad: 768px
* 一般的笔记本:
* 大屏幕显示器:
* 超大屏幕显示器:
* ...

## 建议

* 写样式时尽量让每一个区块能随父容器自适应：不要写死子容器和子元素的属性值，例如，只在父容器统一控制尺寸，子元素不要写死宽度和高度等，而是继承父容器的属性；尽量采用能够自适应的方案，例如绝对定位在某些情况下就不能自适应；
* 尽量把多屏幕下共同的属性提取出来， 不同屏幕下的样式定义里只写这个屏幕下特有的样式，便于修改；
* 尽量把同一个区块不同屏幕的样式写到一块，方便查找和维护；
